spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/thesis
spring.datasource.username=admin
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

###
#Config jwt
#secret key :
danh.jwt.base64-secret=MoBVjEG9ZaqJz8HF1W0KbrimeemTu8ryHUoAqQZB1ITQchzBeDvGb4LDvefT03vqMvHH7J2rPLREQ69JE4vgRw==

#expiration :
danh.jwt.access-token-validity-in-seconds=8640000
danh.jwt.refresh-token-validity-in-seconds=8640000
#
###